create database pesto;

use pesto;

create table CITIES(
    CID INT NOT NULL PRIMARY KEY,
    CITY varchar(20) UNIQUE,
    CITY_STATE varchar(20)
);

create table WAREHOUSES(
    WID INT NOT NULL PRIMARY KEY,
    WNAME varchar(30),
    LOCATION varchar(20),
    EXTRA_CONTEXT json,
    CITY_ID FOREIGN KEY REFERENCES CITIES(CID)
);

create table STORES(
    SID INT NOT NULL PRIMARY KEY,
    STORE_NAME varchar(20),
    LOCATION_CITY varchar(20),
    WAREHOUSE_ID FOREIGN KEY REFERENCES WAREHOUSES(WID)
);

create table CUSTOMER(
    CNO INT NOT NULL PRIMARY KEY,
    CNAME varchar(50),
    ADDR varchar(50),
    CU_CITY varchar(20)
);

create table ORDERS(
    ONO INT NOT NULL PRIMARY KEY,
    ODATE date
    CID FOREIGN KEY REFERENCES CUSTOMER(CNO)
);

create table ITEMS(
    ITEMNO INT,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5,2),
    COST DECIMAL(5,2)
)

create table ITEMORDERS(
    ORDERID FOREIGN KEY REFERENCES ORDERS(ONO)
    ITEMID FOREIGN KEY REFERENCES ITEMS(ITEMNO)
    CUSTOMERID FOREIGN KEY REFERENCES CUSTOMER(CNO)
    ORDERED_QTY INT
)

create table STOREITEMS(
    STOREID FOREIGN KEY REFERENCES ITEMS(SID)
    ITEMID FOREIGN KEY REFERENCES ITEMS(ITEMNO) 
)